AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A starter AWS API Gateway

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
    #  Cors:  "'*'"
      DefinitionUri: src/swagger.yaml
  # ApiFunction: # Adds a GET method at the root resource via an Api event
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Events:
  #       ApiEvent:
  #         Type: Api
  #         Properties:
  #           Path: /
  #           Method: get
  #           RestApiId:
  #             Ref: ApiGatewayApi
  #     Runtime: python3.10
  #     Handler: index.handler
  #     InlineCode: |
  #       def handler(event, context):
  #           return {'body': 'Hello World!', 'statusCode': 200}
  #     Policies:
  #       - AWSLambdaBasicExecutionRole
