AWSTemplateFormatVersion: 2010-09-09
Description: This is a dedicated template for creating an EC2 instance, security group, EIP, and volume.

Parameters:
  AvailabilityZone:
    Description: Enter the availability zone 
    Type: String
    Default: ap-south-1a

  InstanceType:
    Description: Enter the instance type (e.g., t2.micro)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: The instance type must be from allowed values

  Environment:
    Description: Enter the environment type
    Type: String
    AllowedValues:  
      - Dev
      - Prod
      - QA
    Default: Dev
    ConstraintDescription: The enviornment should must be from allowed values

  InstanceName: 
    Description: Enter the instance name
    Type: String
    Default: SchoolMgmtService-Instance

  PortNumber:
    Description: Port number to allow inbound access (e.g., 22 for SSH, 80 for HTTP)
    Type: Number
    Default: 22
 
  IpProtocol:
    Description: Protocol to allow (e.g., tcp, udp, icmp)
    Type: String
    Default: tcp
    AllowedValues: 
      - tcp
      - udp
    ConstraintDescription: Protocol should must be from allowed values
 
  CidrIp:
    Description: CIDR range to allow inbound access (e.g., 0.0.0.0/0 for all IPs)
    Type: String
    Default: "0.0.0.0/0"

  VolumeSize:
    Description: Size of the EBS volume
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 8
    ConstraintDescription: Protocol volume size should be between min and maxvalue included

  DeletionPolicy:
    Description: Deletion policy of the EBS volume
    Type: String
    Default: Delete
    AllowedValues:
      - Delete
      - Snapshot
      - Retain
    ConstraintDescription: DeletionPolicy should must be from allowed values

Mappings:
  AMIMapping:
    us-east-1a:
      AMI: ami-0a3c3a20c09d6f377
    us-east-1b:
      AMI: ami-0b7c2a2c63e9b5d8f
    us-east-1c:
      AMI: ami-0c78a9c48e5a8f3f1

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
     # ImageId: ami-0a3c3a20c09d6f377
      ImageId: !FindInMap [AMIMapping, !Ref AvailabilityZone, AMI]
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref SSHSecurityGroup
      Tags:
        - Key: Name
          Value: !Ref InstanceName
        - Key: Environment 
          Value: !Ref Environment

  CustomEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance
    DependsOn: EC2Instance

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress:
        - CidrIp: !Ref CidrIp
          FromPort: !Ref PortNumber
          IpProtocol: !Ref IpProtocol
          ToPort: !Ref PortNumber 
      Tags:
        - Key: Environment 
          Value: !Ref Environment

  CustomVolume:
    Type: AWS::EC2::Volume
    Properties: 
      Size: !Ref VolumeSize
      Encrypted: true
      AvailabilityZone: !Ref AvailabilityZone  
      Tags:
        - Key: Environment 
          Value: !Ref Environment
    DeletionPolicy: !Ref DeletionPolicy

  MountVolume:
    Type: AWS::EC2::VolumeAttachment
    Properties: 
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref CustomVolume
      Device: /dev/sdh


Outputs:
  ElasticIP:
    Description: "The Elastic IP of the instance"
    Value: !Ref CustomEIP
  
  InstanceID:
    Description: "The Instance ID of the EC2 instance"
    Value: !Ref EC2Instance

  InstanceAvailabilityZone:
    Description: "The Availability Zone of the instance"
    Value: !GetAtt EC2Instance.AvailabilityZone
